version: '3.1'

services:
  wordpress:
    image: wordpress:5.2.4-apache
    restart: always
    ports:
      - 8080:80
    environment:
      - WORDPRESS_DB_HOST=db
      - WORDPRESS_DB_NAME=$MYSQL_DATABASE
      - WORDPRESS_DB_USER=$MYSQL_USER
      - WORDPRESS_DB_PASSWORD=$MYSQL_PASSWORD
    volumes:
      - wordpress:/var/www/html

  db:
    image: mysql:8.0
    restart: always
    command: '--default-authentication-plugin=mysql_native_password'
    volumes:
      - db:/var/lib/mysql

volumes:
  wordpress:
  db: